version: '3.3'
services:
    master:
        ports:
            - '8080:8080'
            - '50000:50000'
        image: shocki/jenkins-master
        secrets:
            - jenkins-user
            - jenkins-pass
        deploy:
            replicas: 1
            placement: 
                constraints:
                    - node.labels.device.group==build-pi

    agent:
        environment:
            - 'JENKINS_URL=http://master:8080'
        image: shocki/jenkins-agent
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock  # Expose the docker daemon in the container
            - /home/jenkins:/home/jenkins # Avoid mysql volume mount issue
        secrets:
            - jenkins-user
            - jenkins-pass

        deploy:
            mode: global
            placement: 
                constraints:
                    - node.labels.device.group==build-pi

secrets:
  jenkins-user:
    external: true
  jenkins-pass:
    external: true
