version: '3.1'
services:

    master:
        image: shocki/jenkins

        ports:
            - '8080:8080'
            - '50000:50000'

        environment:      
            - JENKINS_URL=http://localhost:8080
        
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock  # Expose the docker daemon in the container

        secrets:
            - jenkins-user
            - jenkins-pass

        deploy:
            replicas: 1
            placement: 
                constraints:
                    - node.labels.device.type!=rpi

    agents:
        image: shocki/jenkins-agent

        environment:
            - COMMAND_OPTIONS=-master http://10.0.0.145:8080 -labels 'docker' -executors 4
        hostname: "{{.Node.Hostname}}"

        volumes:
            - /var/run/docker.sock:/var/run/docker.sock

        secrets:
            - jenkins-user
            - source: jenkins-pass
              mode: 0400

        deploy:
            mode: global
            placement: 
                constraints:
                    - node.labels.device.group==build-pi


secrets:
  jenkins-user:
    external: true
  jenkins-pass:
    external: true
