version: '3'

services:

  main:
    image: jenkinsci/jenkins:${TAG:-lts-alpine}
    ports:
      - ${UI_PORT:-8080}:8080
      - ${AGENTS_PORT:-50000}:50000
    environment:
      - JENKINS_OPTS="--prefix=/jenkins"
