version: '3.1'

services:

  master:
    image: shocki/jenkins
    environment:
      - JENKINS_URL=http://localhost:8080
    ports:
      - ${UI_PORT:-8080}:8080
      - ${AGENTS_PORT:-50000}:50000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # Expose the docker daemon in the container
    secrets:
      - jenkins-user
      - jenkins-pass


secrets:
  jenkins-user:
    external: true
  jenkins-pass:
    external: true
