version: '3.1'

services:

  jenkins:
    image: shocki/jenkins
    container_name: jenkins
    volumes:
      - ${JENKINS_PATH}:/var/jenkins_home
    environment:
      - JENKINS_URL=${JENKINS_URL:-http://localhost:8080}
      - JENKINS_USER=${JENKINS_USER}
      - JENKINS_PASS=${JENKINS_PASS}
    ports:
      - ${UI_PORT:-8080}:8080
      - ${AGENTS_PORT:-50000}:50000
