version: '3.1'

services:

  jenkins:
    image: shocki/jenkins
    name: jenkins
    volume:
      - ${JENKINS_PATH}:/var/jenkins_home
    environment:
      - JENKINS_URL=${JENKINS_URL:-http://localhost:8080}
    ports:
      - ${UI_PORT:-8080}:8080
      - ${AGENTS_PORT:-50000}:50000
    secrets:
      - jenkins-user
      - jenkins-pass

secrets:
  jenkins-user:
    external: true
  jenkins-pass:
    external: true
