version: '3.1'

services:

  agents:
    image: shocki/jenkins-agent
    environment:
      - COMMAND_OPTIONS=-master http://10.0.0.145:8080 -labels 'docker' -executors 4
    hostname: "{{.Node.Hostname}}"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    secrets:
      - jenkins-user
      - source: jenkins-pass
        mode: 0400
    deploy:
      mode: global

secrets:
  jenkins-user:
    external: true
  jenkins-pass:
    external: true
